[workspace]
members = [
    # Prover
    #    We don't include `prove` image here since it cannot be built with stable rust
    #    and we don't want to use nightly for the whole workspace
    # "core/bin/prover",
    # Server
    "core/bin/zksync_core",
    "core/bin/admin-tools",
    "core/bin/system-constants-generator",
    # Contract verifier
    "core/bin/contract-verifier",
    # Setup key generator and server: its commented as it cannot be built with stable rust.
    # "core/bin/setup_key_generator_and_server",
    # Verification key generator and server
    "core/bin/verification_key_generator_and_server",
    # Migration to fill events.tx_initiator_address table for old events
    "core/bin/events_tx_initiator_address_migration",
    "core/bin/set_correct_tx_format_for_priority_ops",
    "core/bin/storage_logs_migration",
    # Tool for removing blobs from database
    "core/bin/blob_purger",
    # circuit synthesizer: its commented as it cannot be built with stable rust.
    # "core/bin/circuit_synthesizer",
    # Libraries
    "core/lib/basic_types",
    "core/lib/config",
    "core/lib/contracts",
    "core/lib/crypto",
    "core/lib/circuit_breaker",
    "core/lib/dal",
    "core/lib/db_test_macro",
    "core/lib/eth_client",
    "core/lib/eth_signer",
    "core/lib/mempool",
    "core/lib/merkle_tree",
    "core/lib/object_store",
    "core/lib/mini_merkle_tree",
    "core/lib/prometheus_exporter",
    "core/lib/queued_job_processor",
    "core/lib/state",
    "core/lib/storage",
    "core/lib/types",
    "core/lib/prover_utils",
    "core/lib/utils",
    "core/lib/vlog",
    "core/lib/vm",
    "core/lib/web3_decl",

    # Test infrastructure
    "core/tests/loadnext",
    "core/tests/testkit",

    # SDK section
    "sdk/zksync-rs",
]
resolver = "2"

exclude = [ "core/bin/prover", "core/bin/setup_key_generator_and_server", "core/bin/circuit_synthesizer"]

[profile.test.package.zksync_merkle_tree]
opt-level = 3

